# Generated by Django 2.1 on 2019-09-17 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_auto_20190917_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='createdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 17, 16, 29, 50, 114218), verbose_name='Date'),
        ),
    ]
