# Generated by Django 2.1 on 2019-09-19 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_auto_20190917_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='createdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
